### ISSUE TITLE
"Connection got disposed." when trying to refactor a user-defined type

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#1143]
Reproducible example:

```julia
struct ASDF
    x::Int
    y::Int
    ASDF(x::Int) = new(x, 1)
end

ASDF() = ASDF(2)
```

I tried to refactor `ASDF` to `QWER` and the `"Connection got disposed."` error bubble popped up.

**System info:**

macOS - 10.14.6
VS Code - 1.44.2
Julia Extension - 0.15.25

**Comment by davidanthoff** [comment]
Yes, I can easily reproduce this. The error stack I get locally is:
```
[ Info: Starting the Julia Language Server
[ Info: Language Server crashed with
[ Info: StackOverflowError()
ERROR: StackOverflowError:
Stacktrace:
 [1] iterate at .\array.jl:764 [inlined] (repeats 2 times)
 [2] find_references(::StaticLint.Binding, ::Array{CSTParser.EXPR,1}, ::Bool) at c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\scripts\languageserver\packages\LanguageServer\src\requests\features.jl:179
 [3] find_references(::StaticLint.Binding, ::Array{CSTParser.EXPR,1}, ::Bool) at c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\scripts\languageserver\packages\LanguageServer\src\requests\features.jl:183 (repeats 26126 times)
 [4] find_references at c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\scripts\languageserver\packages\LanguageServer\src\requests\features.jl:176 [inlined]
 [5] find_references(::LanguageServer.TextDocumentIdentifier, ::LanguageServer.Position, ::LanguageServerInstance) at c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\scripts\languageserver\packages\LanguageServer\src\requests\features.jl:163
 [6] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/rename")},LanguageServer.RenameParams}, ::LanguageServerInstance) at c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\scripts\languageserver\packages\LanguageServer\src\requests\features.jl:197
 [7] run(::LanguageServerInstance) at c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl:236
 [8] top-level scope at c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\scripts\languageserver\main.jl:28
 [9] include(::Module, ::String) at .\Base.jl:377
 [10] exec_options(::Base.JLOptions) at .\client.jl:288
 [11] _start() at .\client.jl:484
[Info  - 11:14:46] Connection to server got closed. Server will restart.
[Error - 11:14:46] Request textDocument/rename failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:17988)
	at Object.dispose (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:73286)
	at k.handleConnectionClosed (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:73460)
	at k.handleConnectionClosed (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:7:45941)
	at t (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:71611)
	at r.invoke (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:103835)
	at i.fire (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:104565)
	at K (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:9903)
	at r.invoke (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:103835)
	at i.fire (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:104565)
	at u.fireClose (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:145471)
	at Socket.<anonymous> (c:\Users\david\.vscode\extensions\julialang.language-julia-0.15.25\dist\extension.js:1:146228)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[ Info: Starting the Julia Language Server
```

I think we also have crash reports from this online.
