### ISSUE TITLE
insider 0.17.1: Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by AIxer** [julia-vscode/julia-vscode#1460]
```julia
[Error - 下午2:18:58] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:17817)
	at Object.dispose (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:77701)
	at k.handleConnectionClosed (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:77875)
	at k.handleConnectionClosed (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:132804)
	at t (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:76026)
	at r.invoke (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:107023)
	at i.fire (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:107753)
	at K (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:9732)
	at r.invoke (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:107023)
	at i.fire (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:107753)
	at u.fireClose (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:141758)
	at Socket.<anonymous> (c:\Users\AIxer\.vscode\extensions\julialang.language-julia-insider-0.17.1\dist\extension.js:1:142515)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
```
the error causes the extension restart frequently

**Comment by AIxer** [comment]
`textDocument/hover` is the same case

**Comment by pfitzseb** [comment]
This is the symptom, not the cause -- `Connection got disposed` means the server crashed at some point in the past.

**Comment by AIxer** [comment]
> This is the symptom, not the cause -- `Connection got disposed` means the server crashed at some point in the past.

oh, yes, but I have no idea why it `Request Failed`

**Comment by davidanthoff** [comment]
Did you send a crash report? That is the most helpful thing for us.

**Comment by AIxer** [comment]
I think it has automatically sent a crash report. 😃
