### ISSUE TITLE
Julia Language Server keeps crashing

### ISSUE THREAD

**Issue by Cvikli** [julia-vscode/julia-vscode#1919]
Hey, 

I just checked the latest julia-vscode version 1.1.15 and tha language server keeps crashing for 5 times then it stops.
Fresh Julia: 1.6.0-rc1, Ubuntu 20.04, VSCode: 1.53, node.js: 12.18.1

At first I though I have some precompiled package that cause the problem, but even cleaning everything and starting from fresh julia version it does the same. 

The error that repeats itself:
```
[ Info: Starting the Julia Language Server
[ Info: Symbol server store is at '/home/hm/.config/Code/User/globalStorage/julialang.language-julia/symbolstorev4'.
[ Info: Received new data from Julia Symbol Server.
┌ Warning: Some Julia code in the VS Code extension crashed with
│   e =
│    MethodError: Cannot `convert` an object of type Nothing to an object of type Bool
│    Closest candidates are:
│      convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
│      convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
│      convert(::Type{T}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
│      ...
└ @ Main ~/.vscode/extensions/julialang.language-julia-1.1.15/scripts/error_handler.jl:5
ERROR: MethodError: Cannot `convert` an object of type Nothing to an object of type Bool
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
  ...
Stacktrace:
 [1] DocumentFormat.FormatOptions(indent::Int64, indents::Bool, ops::Bool, tuples::Bool, curly::Bool, calls::Bool, iterOps::Bool, comments::Bool, docs::Bool, lineends::Nothing, keywords::Bool, kwarg::String)
   @ DocumentFormat ~/.vscode/extensions/julialang.language-julia-1.1.15/scripts/packages/DocumentFormat/src/DocumentFormat.jl:11
 [2] request_julia_config(server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
   @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.1.15/scripts/packages/LanguageServer/src/requests/workspace.jl:117
 [3] initialized_notification(params::LanguageServer.InitializedParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
   @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.1.15/scripts/packages/LanguageServer/src/requests/init.jl:178
 [4] (::LanguageServer.var"#112#145"{LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.InitializedParams)
   @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.1.15/scripts/packages/LanguageServer/src/languageserverinstance.jl:285
 [5] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
   @ JSONRPC ~/.vscode/extensions/julialang.language-julia-1.1.15/scripts/packages/JSONRPC/src/typed.jl:66
 [6] run(server::LanguageServerInstance)
   @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.1.15/scripts/packages/LanguageServer/src/languageserverinstance.jl:310
 [7] top-level scope
   @ ~/.vscode/extensions/julialang.language-julia-1.1.15/scripts/languageserver/main.jl:59
[Info  - 4:25:32 PM] Connection to server got closed. Server will restart.
[Error - 4:25:32 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:177140)
	at Object.dispose (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:61757)
	at x.handleConnectionClosed (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:61969)
	at x.handleConnectionClosed (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:59029)
	at t (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:60062)
	at invoke (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:116271)
	at o.fire (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:117032)
	at Y (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:166502)
	at invoke (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:116271)
	at o.fire (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:117032)
	at m.fireClose (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:156575)
	at Socket.<anonymous> (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:158155)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
[Error - 4:25:32 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:177140)
	at Object.dispose (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:61757)
	at x.handleConnectionClosed (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:61969)
	at x.handleConnectionClosed (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:59029)
	at t (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:60062)
	at invoke (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:116271)
	at o.fire (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:117032)
	at Y (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:166502)
	at invoke (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:116271)
	at o.fire (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:117032)
	at m.fireClose (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:156575)
	at Socket.<anonymous> (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:158155)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
[Error - 4:25:32 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:177140)
	at Object.dispose (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:61757)
	at x.handleConnectionClosed (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:61969)
	at x.handleConnectionClosed (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:59029)
	at t (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:60062)
	at invoke (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:116271)
	at o.fire (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:117032)
	at Y (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:166502)
	at invoke (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:116271)
	at o.fire (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:1:117032)
	at m.fireClose (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:156575)
	at Socket.<anonymous> (/home/hm/.vscode/extensions/julialang.language-julia-1.1.15/dist/extension.js:7:158155)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:674:12)
...
```
The error sounds clear but I just can't allocate the problem exactly. 

I barely never had a version that didn't crash I just wanted to know whether this is only my case and everybody else's language server works properly.  

Any idea in case someone's language server worked?

**Comment by ZacLN** [comment]
Hi, we've seen this and have a fix at the ready: https://github.com/julia-vscode/LanguageServer.jl/issues/884. We'll be pushing a new release soon that'll include the above fix
