### ISSUE TITLE
Execute code command fails after REPL restart

### ISSUE THREAD

**Issue by yha** [julia-vscode/julia-vscode#1978]
I find that restarting julia ("Julia: Stop REPL") pretty consistently makes execution commands (alt/shift+enter) fail.
I see one of three behaviors after a restart:
1. (most common) the first execute command does nothing, the developer console says:
```
[[object Object]]listen EADDRINUSE: address already in use \\.\pipe\vsc-julia-repl-8224
$onExtensionRuntimeError @ /C:/Users/sternlab/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1961
/C:/Users/sternlab/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1961 
```
```
Error: listen EADDRINUSE: address already in use \\.\pipe\vsc-julia-repl-8224
	at Server.setupListenHandle [as _listen2] (net.js:1296:21)
	at listenInCluster (net.js:1361:12)
	at Server.listen (net.js:1458:5)
	at c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\dist\extension.js:1:142996
	at c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\dist\extension.js:1:143008
	at Generator.next (<anonymous>)
	at c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\dist\extension.js:1:141176
	at new Promise (<anonymous>)
	at r (c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\dist\extension.js:1:140921)
	at S (c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\dist\extension.js:1:141989)
	at c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\dist\extension.js:1:148903
	at Generator.next (<anonymous>)
	at c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\dist\extension.js:1:141176
	at new Promise (<anonymous>)
	at r (c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\dist\extension.js:1:140921)
	at oe (c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\dist\extension.js:1:148727)
	at c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\dist\extension.js:1:154499
	at b._executeContributedCommand (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88517)
	at b.$executeContributedCommand (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88849)
	at p._doInvokeHandler (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:10276)
	at p._invokeHandler (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9968)
	at p._receiveRequest (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8638)
	at p._receiveOneMessage (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:7440)
	at c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:5568
	at v.fire (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:29104
	at v.fire (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at t._receiveMessage (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:20765)
	at c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:17659
	at v.fire (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at u.acceptChunk (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12880)
	at c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12228
	at Socket.m (c:\Users\sternlab\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:12375)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```
subsequent executions may open a notification: "Running the contributed command: 'language-julia.executeCodeBlockOrSelectionAndMove' failed.", or may succeed.

2. vscode just completely becomes unresponsive after the next execute command.

3. (usually only on the second restart) REPL says
```
ERROR: LoadError: IOError: connect: no such file or directory (ENOENT)
Stacktrace:
 [1] wait_connected(::Base.PipeEndpoint) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Sockets\src\Sockets.jl:525
 [2] connect at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Sockets\src\Sockets.jl:560 [inlined]  
 [3] connect at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Sockets\src\PipeServer.jl:97 [inlined]
 [4] serve(::String; is_dev::Bool, crashreporting_pipename::String) at c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\scripts\packages\VSCodeServer\src\VSCodeServer.jl:84
 [5] top-level scope at c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\scripts\terminalserver\terminalserver.jl:28
 [6] include(::Function, ::Module, ::String) at .\Base.jl:380
 [7] include(::Module, ::String) at .\Base.jl:368
 [8] exec_options(::Base.JLOptions) at .\client.jl:296
 [9] _start() at .\client.jl:506
in expression starting at c:\Users\sternlab\.vscode\extensions\julialang.language-julia-insider-1.1.31\scripts\terminalserver\terminalserver.jl:7
```

**Comment by pfitzseb** [comment]
I can't repro this, even when trying to start a new session very quickly after killing the active one. #1980 might fix the symptoms but not the cause of the issue.
