### ISSUE TITLE
On julia 1.6, `@edit` seems broken: SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by akosuas** [julia-vscode/julia-vscode#2123]
I'm using the vscode julia REPL. On julia 1.5.x, `@edit` used to work and would open the code in the vscode editor. Since 1.6.x, I get the following error:

```
julia> @edit sin(1)
julia> ~/julia-1.6.1/share/julia/base/math.jl:1
# This file is a part of Julia. License is MIT: https://julialang.org/license
^
SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

# AT THIS POINT I INTERRUPT WITH CTRL + C

^CERROR: InterruptException:
Stacktrace:
 [1] poptask(W::Base.InvasiveLinkedListSynchronized{Task})
   @ Base ./task.jl:760
 [2] wait
   @ ./task.jl:768 [inlined]
 [3] wait(c::Base.GenericCondition{ReentrantLock})
   @ Base ./condition.jl:106
 [4] take_buffered(c::Channel{Any})
   @ Base ./channels.jl:389
 [5] take!
   @ ./channels.jl:383 [inlined]
 [6] iterate(c::Channel{Any}, state::Nothing)
   @ Base ./channels.jl:465
 [7] macro expansion
   @ ~/.vscode-server/extensions/julialang.language-julia-1.1.38/scripts/packages/JSONRPC/src/core.jl:99 [inlined]
 [8] (::VSCodeServer.JSONRPC.var"#1#3"{VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}})()
   @ VSCodeServer.JSONRPC ./task.jl:411
   ```

This is on Julia 1.6.1, julia-vscode 1.1.38. It is running on a linux server with VSCode Remote SSH.

**Comment by pfitzseb** [comment]
Seems like https://github.com/julia-vscode/julia-vscode/issues/2057. I don't think we have a release with that fix out yet.

**Comment by akosuas** [comment]
Thanks, didn't spot that but it looks similar. I'll wait for a release and report back.
