### ISSUE TITLE
Julia Language Server crashed

### ISSUE THREAD

**Issue by 0xDBFB7** [julia-vscode/julia-vscode#2380]
Hi! Great piece of software. I hope I'm providing enough information - is there a crash report I should be attaching somehow?

I get the following error on startup when installing the extension with Julia 1.6.1. (here the output is from debug mode from source):

```
Activating extension language-julia
src/extension.ts:51
(node:18618) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.
/usr/share/code/resources/app/out/bootstrap-fork.js:5
rejected promise not handled within 1 second: Error: Connection to server got closed. Server will not be restarted.
/usr/share/code/resources/app/out/bootstrap-fork.js:5
stack trace: Error: Connection to server got closed. Server will not be restarted.
	at LanguageClient.handleConnectionClosed (/home/arthurdent/Downloads/julia-vscode-dev/julia-vscode/dist/extension.js:66739:47)
	at LanguageClient.handleConnectionClosed (/home/arthurdent/Downloads/julia-vscode-dev/julia-vscode/dist/extension.js:70591:15)
	at closeHandler (/home/arthurdent/Downloads/julia-vscode-dev/julia-vscode/dist/extension.js:66708:18)
	at CallbackList.invoke (/home/arthurdent/Downloads/julia-vscode-dev/julia-vscode/dist/extension.js:62307:39)
	at Emitter.fire (/home/arthurdent/Downloads/julia-vscode-dev/julia-vscode/dist/extension.js:62369:36)
	at closeHandler (/home/arthurdent/Downloads/julia-vscode-dev/julia-vscode/dist/extension.js:61383:26)
	at CallbackList.invoke (/home/arthurdent/Downloads/julia-vscode-dev/julia-vscode/dist/extension.js:62307:39)
	at Emitter.fire (/home/arthurdent/Downloads/julia-vscode-dev/julia-vscode/dist/extension.js:62369:36)
	at StreamMessageReader.fireClose (/home/arthurdent/Downloads/julia-vscode-dev/julia-vscode/dist/extension.js:63053:27)
	at Socket.<anonymous> (/home/arthurdent/Downloads/julia-vscode-dev/julia-vscode/dist/extension.js:63138:42)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
	at Pipe.callbackTrampoline (internal/async_hooks.js:131:14)
```

I have set the binpath correctly. This julia has been PackageCompiled with Plots.

Second, and this is probably related to the crashed server, if I select "julia: Execute file in REPL" in a file's context menu in the tree, the file is executed fine:

```julia
[ Info: Precompiling VSCodeServer [9f5989ce-84fe-42d4-91ec-6a7a8d53ed0f]
<output>
julia>
```

But adding a keyboard shortcut and hitting it yields

> Running the contributed command: 'language-julia.executeFile' failed.

Sorry for all the trouble!

(p.s. might be self-evident, but might be useful to mention in CONTRIBUTING.md to check that nodejs is a recent version - really weird errors otherwise)

**Comment by davidanthoff** [comment]
Did you replace the default sysimage with a custom compiled one? We don't support that scenario, so if that is the case, that would probably explain the problem.

Otherwise: do you have crash reporting enabled? That is the best way to send us error information.

**Comment by davidanthoff** [comment]
Closing as outdated: the language server now requires Julia 1.11 or newer (it refuses to start below that), so the configuration in this report is no longer supported. Juliaup, environment discovery and language server startup have all been reworked since as well.

If you hit something similar on a current setup, please open a new issue with the details and we will take a look.
