### ISSUE TITLE
JuliaFormatter 1 usage causing LS restarts

### ISSUE THREAD

**Issue by anandijain** [julia-vscode/julia-vscode#2905]
my .JuliaFormatter.toml has `style = "sciml"` and when I right click -> "Format Document", the LS server seems to crash and require reloading the cache. 

```julia
┌ Error: Some Julia code in the VS Code extension crashed
└ @ Main ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/error_handler.jl:15
ERROR: AssertionError: currently .JuliaFormatter.toml accepts only "default" or "yas" or "blue" for the style configuration
Stacktrace:
  [1] parse_config(tomlfile::String)
    @ JuliaFormatter ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/JuliaFormatter/src/JuliaFormatter.jl:779
  [2] get_juliaformatter_config(doc::LanguageServer.Document, server::LanguageServerInstance)
    @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/LanguageServer/src/requests/features.jl:156
  [3] textDocument_range_formatting_request(params::LanguageServer.DocumentRangeFormattingParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
    @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/LanguageServer/src/requests/features.jl:244
  [4] (::LanguageServer.var"#97#98"{typeof(LanguageServer.textDocument_range_formatting_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.DocumentRangeFormattingParams)
    @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/LanguageServer/src/languageserverinstance.jl:251
  [5] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
    @ JSONRPC ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/JSONRPC/src/typed.jl:67
  [6] run(server::LanguageServerInstance)
    @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/LanguageServer/src/languageserverinstance.jl:369
  [7] top-level scope
    @ ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/languageserver/main.jl:96
  [8] include(mod::Module, _path::String)
    @ Base ./Base.jl:422
  [9] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:303
 [10] _start()
    @ Base ./client.jl:522
[Info  - 9:24:31 AM] Connection to server got closed. Server will restart.
[Error - 9:24:31 AM] Request textDocument/rangeFormatting failed.
Error: Connection got disposed.
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at fireClose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 9:24:31 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at fireClose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 9:24:31 AM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at fireClose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 9:24:31 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at fireClose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 9:24:31 AM] Request textDocument/completion failed.
Error: Connection got disposed.
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at fireClose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[Error - 9:24:31 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at x.handleConnectionClosed (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at apply (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at a.call [as invoke] (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at r.fire (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at fireClose (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at Socket.<anonymous> (/Users/anand/.vscode/extensions/julialang.language-julia-1.6.17/node_modules/vscode-jsonrpc/lib/common/messageReader.js:125:42)
    at Socket.emit (node:events:402:35)
    at Pipe.<anonymous> (node:net:687:12)
[ Info: Starting the Julia Language Server
[ Info: Symbol server store is at '/Users/anand/Library/Application Support/Code/User/globalStorage/julialang.language-julia/symbolstorev5'.
[ Info: Starting LS at 1653582274
[ Info: All cache files downloaded.
[ Info: Loading Graphs from cache...
[ Info: Loading Statistics from cache... (0%)
```

**Comment by davidanthoff** [comment]
The version we ship in the extension does not yet use the latest JuliaFormatter, you'll have to wait a bit for that.

BUT, an incorrect value in the config file should still not crash everything, so that is just a bug :)
