### ISSUE TITLE
"Execute in REPL" cannot create terminal in editor a second time

### ISSUE THREAD

**Issue by mind6** [julia-vscode/julia-vscode#3141]
Open a one line file like:
```Julia
println("hello there")
```
Comment out the code in  `~\.julia\config\startup.jl`.

In `settings.json` set the integrated terminal's default location to "editor"
```	
{
...
"terminal.integrated.defaultLocation": "editor",
...
}
```

Run the "Execute active file in REPL" command either from the UI or command search box.

Press Ctrl-D to quite the REPL.

Run the same command again.

On my Windows setup `vscode v1.72.2/julia-vscode v1.38.2`, the second and future launches will fail to start; it produces this message in `Log (Extension Host)`
```
[exthost] [error] TypeError: Cannot read properties of undefined (reading 'sendRequest')
    at c:\Users\kirby\.vscode\extensions\julialang.language-julia-1.38.2\src\interactive\repl.ts:627:24
    at Generator.next (<anonymous>)
    at a (c:\Users\kirby\.vscode\extensions\julialang.language-julia-1.38.2\src\interactive\profiler.ts:498:5) language-julia.executeActiveFile {"value":"julialang.language-julia","_lower":"julialang.language-julia"}

```

After "reload window" command this behavior is reset and I can run the REPL exactly one time. This problem doesn't exist for me if I open the integrated terminal in "view" instead of "editor".

**Comment by pfitzseb** [comment]
Upstream issue: https://github.com/microsoft/vscode/issues/152302.

You can always work around it by using the `Julia: Stop REPL` command after the current REPL has been closed.
