### ISSUE TITLE
Cannot start LS

### ISSUE THREAD

**Issue by ValentinKaisermayer** [julia-vscode/julia-vscode#3216]
```
Error: command 'UpdateDocstringSignature' already exists
    at s.registerCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:106489)
    at Object.registerCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:29961)
    at t.ExecuteCommandFeature.register (c:\Users\KaisermayerV\.vscode\extensions\julialang.language-julia-1.38.2\node_modules\vscode-languageclient\lib\common\executeCommand.js:50:52)
    at t.ExecuteCommandFeature.initialize (c:\Users\KaisermayerV\.vscode\extensions\julialang.language-julia-1.38.2\node_modules\vscode-languageclient\lib\common\executeCommand.js:30:14)
    at k.initializeFeatures (c:\Users\KaisermayerV\.vscode\extensions\julialang.language-julia-1.38.2\node_modules\vscode-languageclient\lib\common\client.js:1286:21)
    at k.listen [as doInitialize] (c:\Users\KaisermayerV\.vscode\extensions\julialang.language-julia-1.38.2\node_modules\vscode-languageclient\lib\common\client.js:823:18)
    at k.start (c:\Users\KaisermayerV\.vscode\extensions\julialang.language-julia-1.38.2\node_modules\vscode-languageclient\lib\common\client.js:704:24)
```

VS Code extension: 1.38.2
```julia
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 12 virtual cores
```

**Comment by ValentinKaisermayer** [comment]
Works on the pre-release version

**Comment by davidanthoff** [comment]
Closing as outdated: the language server now requires Julia 1.11 or newer (it refuses to start below that), so the configuration in this report is no longer supported. Juliaup, environment discovery and language server startup have all been reworked since as well.

If you hit something similar on a current setup, please open a new issue with the details and we will take a look.
