### ISSUE TITLE
Configuration weirdness with juliaup and dual WSL and Windows

### ISSUE THREAD

**Issue by timholy** [julia-vscode/julia-vscode#3336]
In the past I've modified my vscode julia executable settings and I seem to be having some trouble putting them back. One complexity is that I have julia installed (via `juliaup`) on both WSL and Windows.

## Julia version chosen by vscode (Windows)

Hitting Ctrl-J, selecting "Output", and viewing the log for "Julia Language Server" yields these as its first few lines:

```
The latest version of Julia in the `release` channel is 1.9.1+0.x64.w64.mingw32. You currently have `1.8.5+0.x64.w64.mingw32` installed. Run:

  juliaup update

to install Julia 1.9.1+0.x64.w64.mingw32 and update the `release` channel to that version.
  Activating project at `c:\Users\timho\.vscode\extensions\julialang.language-julia-1.47.2\scripts\environments\languageserver\v1.8`
```

However, in powershell I get

```
PS C:\Users\timho> juliaup status
 Default  Channel  Version                  Update
---------------------------------------------------
          1.8      1.8.5+0.x64.w64.mingw32
          1.9      1.9.1+0.x64.w64.mingw32
       *  release  1.9.1+0.x64.w64.mingw32
PS C:\Users\timho> juliaup update
PS C:\Users\timho>
```

So it appears to be installed. 

## Failure to launch (WSL)

In the Julia extension settings I have the Julia executable path set as follows:
- `User`: `"C:\\Users\\timho\\AppData\\Local\\Microsoft\\WindowsApps\\julia.exe`
- `Remote [WSL: Ubuntu]`: `/home/tim/.juliaup/bin/julia`

This seems to work on Windows but not WSL; for example, latex-completion works when I run vscode in Windows but not WSL. On WSL, I get a log filled with error messages, of which a sample is
```
[Error - 2:04:32 PM] Client Julia Language Server: connection to server is erroring. Shutting down server.
[Error - 2:04:32 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
    at _.shutdown (/home/tim/.vscode-server/extensions/julialang.language-julia-1.47.2/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at _.stop (/home/tim/.vscode-server/extensions/julialang.language-julia-1.47.2/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at _.stop (/home/tim/.vscode-server/extensions/julialang.language-julia-1.47.2/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at _.handleConnectionError (/home/tim/.vscode-server/extensions/julialang.language-julia-1.47.2/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Error - 2:04:32 PM] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 2:04:32 PM] Julia Language Server client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 2:04:32 PM] Connection to server got closed. Server will restart.
true
Error: The Julia launcher failed to figure out which juliaup channel to use.
```
The most telling seems to be the last line,

```
Error: The Julia launcher failed to figure out which juliaup channel to use.
```

However, in the terminal
```
tim@diva:~$ juliaup status
 Default  Channel  Version                Update 
-------------------------------------------------
          1.0      1.0.5+0.x64.linux.gnu         
          1.6      1.6.7+0.x64.linux.gnu         
          1.7      1.7.3+0.x64.linux.gnu         
          1.8      1.8.5+0.x64.linux.gnu         
       *  1.9      1.9.1+0.x64.linux.gnu         
          release  1.9.1+0.x64.linux.gnu         
```
and launching `julia` from the terminal works as expected.

**Comment by davidanthoff** [comment]
I think unless you want to do something very special, the best thing to do is just always leave Julia executable path empty if you use Juliaup, in theory it should then just always work (TM).

**Comment by timholy** [comment]
That does seem to fix it! Perhaps the error message could specify that leaving it blank is an option?

Feel free to close whenever.

**Comment by davidanthoff** [comment]
Closing as outdated: the language server now requires Julia 1.11 or newer (it refuses to start below that), so the configuration in this report is no longer supported. Juliaup, environment discovery and language server startup have all been reworked since as well.

If you hit something similar on a current setup, please open a new issue with the details and we will take a look.
