### ISSUE TITLE
language client is not ready

### ISSUE THREAD

**Issue by hzgzh** [julia-vscode/julia-vscode#671]
[2019-01-26 19:29:43.822] [renderer1] [error] Language client is not ready yet: Error: Language client is not ready yet
	at LanguageClient.sendNotification (C:\Users\hzgzh\.vscode\extensions\julialang.language-julia-0.11.4\node_modules\vscode-languageclient\lib\client.js:1729:19)
	at C:\Users\hzgzh\.vscode\extensions\julialang.language-julia-0.11.4\out\jlpkgenv.js:27:26
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\hzgzh\.vscode\extensions\julialang.language-julia-0.11.4\out\jlpkgenv.js:4:58)
	at <anonymous>

**Comment by davidanthoff** [comment]
@hzgzh is this still an issue? If so, can you please reopen this issue and provide us with more information, for example when does this happen, where is this error message shown etc? What versions of things are you using.

**Comment by kongdd** [comment]
I also faced with issue. This problem is quite often in recent days.
```
version: 1.6.11
Language client is not ready yet
```

**Comment by kongdd** [comment]
In my case, `eval line` (ctrl+R) often not work, which gives the error "Language client is not ready yet", and incorrectly eval the first line of my script, other than the selected line.
But `eval selection` works in julia.

**Comment by davidanthoff** [comment]
Closing as outdated: the language server now requires Julia 1.11 or newer (it refuses to start below that), so the configuration in this report is no longer supported. Juliaup, environment discovery and language server startup have all been reworked since as well.

If you hit something similar on a current setup, please open a new issue with the details and we will take a look.
