### ISSUE TITLE
The LanguangeSever alway restart when editing the multi-line docstrings

### ISSUE THREAD

**Issue by shilu1984** [julia-vscode/julia-vscode#780]
Julia codeExtension version: 0.12.beta.2
OS version:Window 7 sp1

I find that the content of OUTLINE alway changes to `Loadign document symbols for 'xxx.jl'` from the symbol list when I typing words in the multiline docstring.

**Comment by ZacLN** [comment]
Hi could you provide some  example code where this is happening (also could you enable the `Julie: Toggle server logs` command)

**Comment by shilu1984** [comment]
```

"""
A very simple example, when I add words here, 
the content of OUTLINE always change to reload symbols.
Deleting words will not change anything. 
I don't know if this is a server restart.
"""
function _rotmatrix(α::Float64)
    s = sind(α)
    c = cosd(α)
    return @SMatrix [c s; -s c]
end

```

**Comment by shilu1984** [comment]
I solve this problem by disable the autosuggentions in strings with settings:
```
"[julia]": {
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": false
        }
    }
```
Therefore, the quickSuggention in typing strings maybe the reason of this issue.

**Comment by ZacLN** [comment]
Use the `View: Toggle Output` command and then select `julia Language Server` from the drop down menu on the right hand size

**Comment by shilu1984** [comment]
```
[ Info: Language Server crashed with
[ Info: ErrorException("type Nothing has no field captures")
ERROR: LoadError: type Nothing has no field captures
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at .\sysimg.jl:18
 [2] splitdrive(::String) at .\path.jl:39
 [3] splitdir at .\path.jl:132 [inlined]
 [4] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/completion")},LanguageServer.CompletionParams}, ::LanguageServerInstance) at c:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\scripts\languageserver\packages\LanguageServer\src\requests\completions.jl:35
 [5] run(::LanguageServerInstance) at c:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl:47
 [6] top-level scope at c:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\scripts\languageserver\main.jl:22
 [7] include at .\boot.jl:326 [inlined]
 [8] include_relative(::Module, ::String) at .\loading.jl:1038
 [9] include(::Module, ::String) at .\sysimg.jl:29
 [10] exec_options(::Base.JLOptions) at .\client.jl:267
 [11] _start() at .\client.jl:436
in expression starting at c:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\scripts\languageserver\main.jl:5
[Info  - 下午3:59:36] Connection to server got closed. Server will restart.
[Error - 下午3:59:36] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Error - 下午3:59:36] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\Shilu-M3800\.vscode\extensions\julialang.language-julia-0.12.0-beta.2\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
```

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/blob/d309635accb00bd070e8b3f500971ab296eabae8/base/path.jl#L37-L40

looks pretty weird.

**Comment by ZacLN** [comment]
temporarily fixed: https://github.com/julia-vscode/LanguageServer.jl/commit/e197e2d2ab61af55de1ec161b44a6b11f8058fac
