### ISSUE TITLE
Julia language server crash on single-quoted multi-line string

### ISSUE THREAD

**Issue by sdewaele** [julia-vscode/julia-vscode#835]
The language server crashes when I enter a multi-line single-quoted string in a .jl file, e.g.
```
"
aaaa

"
```

Julia Language server output:
```
[ Info: Started symbol server
[ Info: store set
[ Info: Language Server crashed with
[ Info: ErrorException("type Nothing has no field captures")
ERROR: LoadError: type Nothing has no field captures
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at .\sysimg.jl:18
 [2] splitdrive(::String) at .\path.jl:39
 [3] splitdir at .\path.jl:132 [inlined]
 [4] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/completion")},LanguageServer.CompletionParams}, ::LanguageServerInstance) at c:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\scripts\languageserver\packages\LanguageServer\src\requests\completions.jl:35
 [5] run(::LanguageServerInstance) at c:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl:47
 [6] top-level scope at c:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\scripts\languageserver\main.jl:24
 [7] include at .\boot.jl:326 [inlined]
 [8] include_relative(::Module, ::String) at .\loading.jl:1038
 [9] include(::Module, ::String) at .\sysimg.jl:29
 [10] exec_options(::Base.JLOptions) at .\client.jl:267
 [11] _start() at .\client.jl:436
in expression starting at c:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\scripts\languageserver\main.jl:7
[Info  - 1:49:01 PM] Connection to server got closed. Server will restart.
[Error - 1:49:01 PM] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Error - 1:49:01 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
[Error - 1:49:01 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\sdwaele\.vscode\extensions\julialang.language-julia-0.12.1\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
[ Info: Started symbol server
[ Info: store set
```

**Comment by ZacLN** [comment]
This looks like the split_drive issue to me? Should be fixed

**Comment by davidanthoff** [comment]
@ZacLN does that mean you did fix this already? That is how I understand it and I'm closing this issue.

**Comment by ZacLN** [comment]
Yep, I think this has been fixed.
