### ISSUE TITLE
LS crashes with StackOverflowError()

### ISSUE THREAD

**Issue by f-t-s** [julia-vscode/julia-vscode#883]
When running the extension on a certain (small) project, the language server keeps crashing with the following error message. I reinstalled multiple times with different versions of Julia, without seeming to be able to resolve the issue. Any ideas? Julia-vscode version is 0.12.3

> [ Info: Started symbol server
[ Info: store set
[ Info: RECEIVED: {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":14181,"rootPath":"/home/f-t-s/Research/KoLesky-code","rootUri":"file:///home/f-t-s/Research/KoLesky-code","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///home/f-t-s/Research/KoLesky-code","name":"KoLesky-code"}]}}
[ Info: 
[ Info: SENT: {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":2,"hoverProvider":true,"completionProvider":{"resolveProvider":false,"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["("]},"definitionProvider":true,"typeDefinitionProvider":false,"implementationProvider":false,"referencesProvider":true,"documentHighlightProvider":false,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"codeActionProvider":false,"documentFormattingProvider":true,"documentRangeFormattingProvider":false,"renameProvider":true,"colorProvider":false,"executeCommandProvider":{"commands":[]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}},"experimental":null}}}
[ Info: TIME:1.3
[ Info: RECEIVED: {"jsonrpc":"2.0","method":"initialized","params":{}}
[ Info: 
[ Info: SENT: {"method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/f-t-s/Research/KoLesky-code/src/CovFuncs.jl","diagnostics":[]},"jsonrpc":"2.0"}
[ Info: TIME:9.5
[ Info: SENT: {"method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/f-t-s/Research/KoLesky-code/src/KoLesky.jl","diagnostics":[]},"jsonrpc":"2.0"}
[ Info: TIME:9.7
[ Info: Language Server crashed with
[ Info: StackOverflowError()
ERROR: LoadError: StackOverflowError:
Stacktrace:
 [1] getproperty at ./Base.jl:20 [inlined]
 [2] ht_keyindex(::Dict{String,SymbolServer.ModuleStore}, ::String) at ./dict.jl:281
 [3] getindex at ./dict.jl:476 [inlined]
 [4] get_root_method(::CSTParser.Binding, ::LanguageServerInstance, ::CSTParser.Binding, ::Array{CSTParser.Binding,1}) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/utils.jl:110
 [5] get_root_method(::CSTParser.Binding, ::LanguageServerInstance, ::CSTParser.Binding, ::Array{CSTParser.Binding,1}) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/utils.jl:111 (repeats 37368 times)
 [6] get_root_method at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/utils.jl:108 [inlined]
 [7] infer_type(::CSTParser.Binding, ::CSTParser.Scope, ::LanguageServerInstance) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/type_inf.jl:19
 [8] add_binding(::CSTParser.EXPR, ::StaticLint.State) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:166
 [9] (::StaticLint.State)(::CSTParser.EXPR) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:56
 [10] (::StaticLint.State)(::CSTParser.EXPR) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:134
 [11] (::StaticLint.State)(::CSTParser.EXPR) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:112
 [12] (::StaticLint.State)(::CSTParser.EXPR) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:134 (repeats 3 times)
 [13] followinclude(::CSTParser.EXPR, ::StaticLint.State) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:209
 [14] (::StaticLint.State)(::CSTParser.EXPR) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:91
 [15] (::StaticLint.State)(::CSTParser.EXPR) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:134
 [16] followinclude(::CSTParser.EXPR, ::StaticLint.State) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:209
 [17] (::StaticLint.State)(::CSTParser.EXPR) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:91
 [18] (::StaticLint.State)(::CSTParser.EXPR) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:134
 [19] scopepass(::LanguageServer.Document) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/StaticLint/src/server.jl:43
 [20] parse_all(::LanguageServer.Document, ::LanguageServerInstance) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/LanguageServer/src/parsing.jl:15
 [21] load_folder(::String, ::LanguageServerInstance) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/LanguageServer/src/requests/init.jl:62
 [22] process(::LanguageServer.JSONRPC.Request{Val{:initialized},Dict{String,Any}}, ::LanguageServerInstance) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/LanguageServer/src/requests/init.jl:101
 [23] run(::LanguageServerInstance) at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:47
 [24] top-level scope at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/main.jl:25
 [25] include at ./boot.jl:328 [inlined]
 [26] include_relative(::Module, ::String) at ./loading.jl:1094
 [27] include(::Module, ::String) at ./Base.jl:31
 [28] exec_options(::Base.JLOptions) at ./client.jl:295
 [29] _start() at ./client.jl:464
in expression starting at /home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/scripts/languageserver/main.jl:7
[Info  - 5:58:59 PM] Connection to server got closed. Server will restart.
[Error - 5:58:59 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-languageclient/lib/client.js:2153:42)
	at LanguageClient.handleConnectionClosed (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-languageclient/lib/main.js:151:15)
	at closeHandler (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-languageclient/lib/client.js:2140:18)
	at CallbackList.invoke (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at StreamMessageReader.fireClose (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.readable.on (/home/f-t-s/.vscode/extensions/julialang.language-julia-0.12.3/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe._handle.close (net.js:606:12)

**Comment by 8uurg** [comment]
The StackOverflowError seems to be the same one as in issue #849 .

**Comment by davidanthoff** [comment]
I'm going to close this issue for now, there have been a lot of updates in the various packages. Please retry once we have a beta for v0.13.0 of the extension out and open a new issue if there are still problems with that. I'll announce the beta on discourse and slack.
